### ISSUE TITLE
klk'kl'lk'

### ISSUE THREAD

**Issue by cylcoder** [sparta-team15/temueats#152]
## Subject
> 50자를 넘으면 안되며 현재 시제로 명령문으로 작성
    > ~기능을 수정했었다 (X)
    > ~기능 수정(O)
> 마침표 금지
> 소문자lk'kl'lk

## Content(내용)
> 필요한 경우 사용하며, 이슈에 대한 설명 작성
> 제목 입력 후 한 줄 띄고 작성하고 한줄에 70자를 넘기지 않는다
> 무엇을 왜 해야되는지를 중심으로 작성
> 현재 시제로 작성

**Comment by jeendale** [comment]
고생하셨습니다!

**Comment by drinkgalaxy** [comment]
고생하셨습니다 ^^
